# Generated by Django 5.1.7 on 2025-06-11 15:30

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_image1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image1')),
                ('news_image2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image2')),
                ('news_image3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image3')),
                ('news_image4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image4')),
                ('news_image5', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image5')),
                ('news_image6', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image6')),
                ('news_image7', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image7')),
                ('news_title', models.CharField(max_length=255)),
                ('news_time', models.DateTimeField(auto_now_add=True)),
                ('news_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TireType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image1')),
                ('image2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image2')),
                ('image3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image3')),
                ('image4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image4')),
                ('image5', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image5')),
                ('image6', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image6')),
                ('image7', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image7')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('negotiable', models.BooleanField(default=False)),
                ('promotion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promotion_end_date', models.DateTimeField(blank=True, null=True)),
                ('model_description', models.TextField()),
                ('in_stock', models.IntegerField()),
                ('profile', models.CharField(max_length=50)),
                ('diameter', models.CharField(max_length=100)),
                ('speed_index', models.CharField(max_length=100)),
                ('load_index', models.CharField(max_length=500)),
                ('load_index_for_double', models.CharField(max_length=200)),
                ('is_favorite', models.BooleanField(default=False)),
                ('favorite_created_at', models.DateTimeField(blank=True, null=True)),
                ('condition', models.BooleanField(default=False)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=255)),
                ('generation', models.CharField(max_length=100)),
                ('modification', models.CharField(max_length=255)),
                ('promotionCategory', models.TextField(blank=True, null=True)),
                ('width', models.CharField(max_length=10)),
                ('fuel_efficiency', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=1)),
                ('wet_grip', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1)),
                ('external_noise_level', models.IntegerField()),
                ('runflat', models.BooleanField(default=False)),
                ('off_road', models.BooleanField(default=False)),
                ('warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.bodytype')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.season')),
                ('tire_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.tiretype')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.DecimalField(choices=[(Decimal('1.0'), '1 ★'), (Decimal('1.5'), '1.5 ★'), (Decimal('2.0'), '2 ★'), (Decimal('2.5'), '2.5 ★'), (Decimal('3.0'), '3 ★'), (Decimal('3.5'), '3.5 ★'), (Decimal('4.0'), '4 ★'), (Decimal('4.5'), '4.5 ★'), (Decimal('5.0'), '5 ★')], decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
