# Generated by Django 5.1.6 on 2025-04-16 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='body_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.bodytype'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.condition'),
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.season'),
        ),
        migrations.AddField(
            model_name='product',
            name='tire_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.tiretype'),
        ),
    ]
