# Generated by Django 5.1.6 on 2025-03-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20250316_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_field',
        ),
    ]
