# Generated by Django 5.1.6 on 2025-04-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
