# Generated by Django 5.1.6 on 2025-04-16 11:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('news_title', models.CharField(max_length=255)),
                ('news_time', models.DateTimeField()),
                ('news_description', models.TextField()),
            ],
        ),
    ]
