# Generated by Django 5.1.6 on 2025-03-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_new_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
