# Generated by Django 5.1.6 on 2025-03-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_manufacturer_delete_manufacturer'),
    ]

    operations = [
    ]
