# Generated by Django 5.1.6 on 2025-03-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20250317_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='model_description',
        ),
    ]
