# Generated by Django 5.1.6 on 2025-03-24 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_description_product_model_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.FloatField(choices=[('1.0', '1 ★'), ('1.5', '1.5 ★'), ('2.0', '2 ★'), ('2.5', '2.5 ★'), ('3.0', '3 ★'), ('3.5', '3.5 ★'), ('4.0', '4 ★'), ('4.5', '4.5 ★'), ('5.0', '5 ★')], validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
