# Generated by Django 5.1.6 on 2025-03-24 12:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.DecimalField(choices=[(Decimal('1.0'), '1 ★'), (Decimal('1.5'), '1.5 ★'), (Decimal('2.0'), '2 ★'), (Decimal('2.5'), '2.5 ★'), (Decimal('3.0'), '3 ★'), (Decimal('3.5'), '3.5 ★'), (Decimal('4.0'), '4 ★'), (Decimal('4.5'), '4.5 ★'), (Decimal('5.0'), '5 ★')], decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))]),
        ),
    ]
