# Generated by Django 5.1.6 on 2025-03-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_characteristics',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
