# Generated by Django 5.1.6 on 2025-03-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_main_characteristics_product_warranty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_characteristics',
        ),
    ]
