# Generated by Django 5.1.2 on 2025-04-11 04:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('news_title', models.CharField(max_length=255)),
                ('news_time', models.DateTimeField()),
                ('news_description', models.TextField()),
            ],
        ),
    ]
