# Generated by Django 5.1.6 on 2025-04-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_delete_news'),
        ('product', '0004_news'),
        ('product', '0012_news'),
    ]

    operations = [
    ]
