# Generated by Django 5.1.6 on 2025-04-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_news'),
        ('product', '0012_news'),
    ]

    operations = [
    ]
