# Generated by Django 5.1.6 on 2025-04-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_merge_0004_news_0012_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
