# Generated by Django 5.1.6 on 2025-04-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_delete_news'),
        ('product', '0014_alter_news_news_time'),
    ]

    operations = [
    ]
