# Generated by Django 5.1.6 on 2025-04-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_image1_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
    ]
