# Generated by Django 5.1.6 on 2025-04-20 15:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_product_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=cloudinary.models.CloudinaryField(default='ken_kaneki_black_reaper', max_length=255, verbose_name='image1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image4'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image5'),
        ),
        migrations.AddField(
            model_name='product',
            name='image6',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image6'),
        ),
        migrations.AddField(
            model_name='product',
            name='image7',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image7'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=cloudinary.models.CloudinaryField(default='ken_kaneki_black_reaper', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
