# Generated by Django 5.1.6 on 2025-04-29 09:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_image',
        ),
        migrations.AddField(
            model_name='news',
            name='news_image1',
            field=cloudinary.models.CloudinaryField(default='http://res.cloudinary.com/dag906vzz/image/upload/nyklxzegegkxm5aeakmq', max_length=255, verbose_name='image1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='news_image2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image2'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_image3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image3'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_image4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image4'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_image5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image5'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_image6',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image6'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_image7',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image7'),
        ),
    ]
