# Generated by Django 5.1.6 on 2025-04-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_news_news_image_news_news_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
