# Generated by Django 5.1.6 on 2025-03-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_product_body_type_product_generation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotion_category',
        ),
    ]
