# Generated by Django 5.1.7 on 2025-05-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_product_favorite_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
