# Generated by Django 5.1.7 on 2025-05-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_product_condition_delete_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.BooleanField(default=False),
        ),
    ]
