# Generated by Django 5.1.6 on 2025-03-13 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_condition_manufacturer_season_tiretype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.condition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='external_noise_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='fuel_efficiency',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='generation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='modification',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='profile',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='promotionCategory',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='promotion_end_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.season'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='tire_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.tiretype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='wet_grip',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
