# Generated by Django 5.1.6 on 2025-03-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_product_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotion_end_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
