# Generated by Django 5.1.6 on 2025-03-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_product_promotion_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotion_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
