# Generated by Django 5.1.6 on 2025-03-13 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_product_promotion_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.season'),
        ),
    ]
