# Generated by Django 5.1.6 on 2025-03-13 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_product_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.season'),
        ),
    ]
