# Generated by Django 5.1.6 on 2025-03-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_product_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='off_road',
        ),
        migrations.RemoveField(
            model_name='product',
            name='runflat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='season',
        ),
    ]
