# Generated by Django 5.1.6 on 2025-03-15 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_remove_product_off_road_remove_product_runflat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.season'),
            preserve_default=False,
        ),
    ]
