# Generated by Django 5.1.6 on 2025-03-15 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_bodytype_alter_product_promotioncategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='body_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.bodytype'),
            preserve_default=False,
        ),
    ]
