# Generated by Django 5.1.6 on 2025-04-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
